server {
    listen: 8080
    error_page default: ../demo/errors/default.html

    root: ../demo

    route /cgi-bin {
        root: ../demo
        methods: GET, POST

        cgi .py: /usr/bin/python3
    }
}
