server {
    listen: 8080
    error_page default: ../demo/errors/default.html

    max_body_size: 1m
    root: ../demo
    index: index.html
    methods: GET

    route / {
    }

    route /data {
        root: ../demo/data
        index: data.html
    }
}
