server {
	listen: 8080 

	# Global config
	root: ./
  index: index.html, styles.css
	methods: GET
	max_body_size: 1m

	# Global error pages
	error_page default: ../common/errors/default.html
	error_page 404: ../common/errors/404.html

	route / {
		root: ./html
		index: index.html
	}

	route /css {
		root: ../common/css
	}

	route /js {
		root: ../common/js
	}

	route /assets {
		root: ../common/assets
	}

	route /old {
		redirect: /
	}

	route /uploads {
		root: ./uploads
		methods: GET, POST, DELETE
		max_body_size: 100m 
		upload: on
		upload_dir: ./uploads
		autoindex: on
	}

	route /messages {
		root: ./messages
		methods: GET, POST
		upload: on
		upload_dir: ./messages
		autoindex: on
	}

	#route /cgi {
		#root: ./cgi
		#cgi .php: /usr/bin/php-cgi
	#}
}
