server {
	listen: 8080 

	# Global config
	root: ./
	methods: GET
	max_body_size: 1m

	# Global error pages
	error_page default: ./errors/default.html
	error_page 404: ./errors/404.html

	route / {
		root: ./www/html
		index: index.html
	}

	route /css {
		root: ./www/css
	}

	route /js {
		root: ./www/js
	}

	route /assets {
		root: ./www/assets
	}

	route /old {
		redirect: /
	}

	route /uploads {
		root: ./uploads
		methods: GET, POST, DELETE
		max_body_size: 100m 
		upload: on
		upload_dir: .
		autoindex: on
	}

	#route /messages {
		#root: ./messages
		#methods: GET, POST
		#upload: on
		#upload_dir: .
		#autoindex: on
	#}

	#route /cgi {
		#root: ./cgi
		#cgi .php: /usr/bin/php-cgi
		#cgi .py: /usr/bin/python3
	#}
}


server {
	listen: 8081

	# Global config
	root: ./
	methods: GET, POST
	max_body_size: 1m

	# Global error pages
	error_page default: ./errors/default.html
	error_page 404: ./errors/404.html

	cgi .php: /usr/bin/php-cgi
	cgi .py: /usr/bin/python3
	route /css {
		root: ./www/css
	}
	route /assets {
		root: ./www/assets
	}
	route / {
		root: ../www
		index: index.html
	}
}


server {
	listen: 8082

	# Global config
	# relative path was assumed somewhere 
	root: ./
	methods: GET, POST
	max_body_size: 1m

#kd
	fcgi_sock: ../bonus/.php-fpm/SOCK
	# pycgi_dir: ../bonus/legacy-cgi-2.6

	# Global error pages
	error_page default: ./errors/default.html
	error_page 404: ./errors/404.html
	error_page 500: ./errors/500.html
	error_page 503: ./errors/503.html
	error_page 504: ./errors/504.html

	route /css {
		root: ./www/css
	}
	route /assets {
		root: ./www/assets
	}
	route / {
		root: ../www/kd
		index: index.html
		cgi .php: /usr/bin/php-cgi
		cgi .py: /usr/bin/python
		cgi .pl: /usr/bin/perl
	}
	route /files {
# Directory listing for /media/kdonlon/data/Documents/42/webserv/git/tst/server/../../demo/./
		autoindex: on
		root: ../www/kd/files
		
	}
	route /vids {
		root: /home/kdonlon/Videos
		methods: GET
		max_body_size: 100m 
		autoindex: on
	}

	route /uploads {
		root: ../www/kd/uploads
		methods: GET, POST, DELETE
		max_body_size: 5m 
		upload: on
		upload_dir: .
		autoindex: on
	}
}

# .cgi files should return an ERROR if CGI is not enabled from that directory
# keep-alive
	# we should only return keep-alive .. if the request asked for it (?)

# default error page .. should handle ANY error code

# To upload a file using a POST request, the client must send data encoded as multipart/form-data using an HTML form or a FormData JavaScript object. The server then intercepts this request, parses the multi-part stream, and saves the binary file contents to a permanent or temporary directory on the disk

# <form action="/upload" method="POST" enctype="multipart/form-data">
#   <input type="file" name="myFile" />
#   <button type="submit">Upload</button>
# </form>

# curl -i -X POST -H "Content-Type: multipart/form-data" \
# 	 -F "data=@www/files/earth.jpg" http://127.0.0.1:8082/media/1234/uploads


# https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html


# Request
# spaces should not be allowed in Header KEYS
# should we validate Host:

# Q: Supported Media Type
# Q: location (forwarding)
