server {
	listen: 8080 

	# Global config
	root: ./
	methods: GET
	max_body_size: 1m

	# Global error pages
	error_page default: ./errors/default.html
	error_page 404: ./errors/404.html

	route / {
		root: ./www/html
		index: index.html
	}

	route /css {
		root: ./www/css
	}

	route /js {
		root: ./www/js
	}

	route /assets {
		root: ./www/assets
	}

	route /old {
		redirect: /
	}

	route /uploads {
		root: ./uploads
		methods: GET, POST, DELETE
		max_body_size: 100m 
		upload: on
		upload_dir: .
		autoindex: on
	}

	#route /messages {
		#root: ./messages
		#methods: GET, POST
		#upload: on
		#upload_dir: .
		#autoindex: on
	#}

	#route /cgi {
		#root: ./cgi
		#cgi .php: /usr/bin/php-cgi
		#cgi .py: /usr/bin/python3
	#}
}


server {
	listen: 8081

	# Global config
	root: ./
	methods: GET, POST
	max_body_size: 1m

	# Global error pages
	error_page default: ./errors/default.html
	error_page 404: ./errors/404.html

	cgi .php: /usr/bin/php-cgi
	cgi .py: /usr/bin/python3
	route / {
		root: ../tst/server/www
		index: index.html
	}
}


server {
	listen: 8082

	# Global config
	# relative path was assumed somewhere 
	root: ./
	methods: GET, POST
	max_body_size: 1m

	# Global error pages
	error_page default: ./errors/default.html
	error_page 404: ./errors/404.html

	route / {
		root: ../tst/server/www
		index: index.html
		cgi .php: /usr/bin/php-cgi
		cgi .py: /usr/bin/python3
		cgi .pl: /usr/bin/perl

		# route /files {
		# 	autoindex: on
		# }
	}
	route /files {
# Directory listing for /media/kdonlon/data/Documents/42/webserv/git/tst/server/../../demo/./
		autoindex: on
		root: ../tst/server/www/files
		
	}
}

# .cgi files should return an ERROR if CGI is not enabled from that directory
# keep-alive
	# we should only return keep-alive .. if the request asked for it (?)

# default error page .. should handle ANY error code