server {
	listen: 8080 

	# Global config
	root: ./
	methods: GET
	max_body_size: 1m

	# Global error pages
	error_page default: ./errors/default.html
	error_page 404: ./errors/404.html

	route / {
		root: ./www/html
		index: index.html
	}

	route /css {
		root: ./www/css
	}

	route /js {
		root: ./www/js
	}

	route /images {
		root: ./www/images
	}

	route /old {
		redirect: /
	}

	route /uploads {
		root: ./uploads
		methods: GET, POST, DELETE
		max_body_size: 100m 
		upload: on
		upload_dir: .
		autoindex: on
	}

	route /cgi {
		root: ./cgi
		cgi .php: /usr/bin/php-cgi
		cgi .py: /usr/bin/python3
	}
}
